version: '3.8'

services:
  backend:
    build: ./netpulse_backend
    ports:
      - "8000:8000"
    volumes:
      - ./netpulse_backend:/app
    env_file:
      - ./netpulse_backend/.env
    depends_on:
      - db
      - redis
      - rabbitmq

  frontend:
    build: ./netpulse_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./netpulse_frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  celery-worker:
    build: ./netpulse_backend
    command: celery -A app.core.celery_config worker --loglevel=info
    volumes:
      - ./netpulse_backend:/app
    env_file:
      - ./netpulse_backend/.env
    depends_on:
      - db
      - redis
      - rabbitmq

  celery-beat:
    build: ./netpulse_backend
    command: celery -A app.core.celery_config beat --loglevel=info
    volumes:
      - ./netpulse_backend:/app
    env_file:
      - ./netpulse_backend/.env
    depends_on:
      - db
      - redis
      - rabbitmq

  db:
    image: timescale/timescaledb:latest-pg15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=netpulse
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=netpulse
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=netpulse
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # Monitoring Stack
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"  # Different port to avoid conflict with frontend
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  postgres_data:
  rabbitmq_data:
  prometheus_data:
  grafana_data:
